services:
  mariadb:
    build:
      context: requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    # TODO (Dia 2): escribir requirements/mariadb/Dockerfile + tools/entrypoint.sh

  wordpress:
    build:
      context: requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart: unless-stopped
    # TODO (Dia 3): escribir requirements/wordpress/Dockerfile + tools/entrypoint.sh

  nginx:
    build:
      context: requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped
    # TODO (Dia 7): escribir requirements/nginx/Dockerfile + conf/nginx.conf (TLSv1.2/1.3 only)

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/paperez-/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/paperez-/data/wordpress

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
