# TODO (Dia 7)
# - FROM debian:<penultima_stable>-slim  (o alpine:<penultima_stable>) -- NUNCA :latest
# - instalar nginx + openssl
# - generar certificado autofirmado para DOMAIN_NAME (paperez-.42.fr) en build o entrypoint
# - COPY conf/nginx.conf:
#     * listen 443 ssl;
#     * ssl_protocols TLSv1.2 TLSv1.3;  (nada de TLSv1/TLSv1.1)
#     * fastcgi_pass wordpress:9000;
#     * unico punto de entrada del stack (puerto 443 unicamente)
# - CMD/ENTRYPOINT: nginx -g "daemon off;"
